    spec:

      imagePullSecrets:
      - name: ecr-secret

      containers:
      - name: backend

        image: 755395261632.dkr.ecr.us-east-1.amazonaws.com/platform/tic-tac-toe/back-end:v3

        ports:
        - containerPort: 8000

        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_URL

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password

        - name: DB_HOST
          value: postgres

        - name: DB_NAME
          value: tictactoe

        resources:
          requests:
            cpu: 50m
            memory: 64Mi

          limits:
            cpu: 200m
            memory: 256Mi