apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tic-tac-toe
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Mallikarjun-Atanoor/k8s-gitops-microservices.git
    targetRevision: HEAD
    path: tic-tac-toe
  destination:
    server: https://kubernetes.default.svc
    namespace: tic-tac-toe
  syncPolicy:
    automated:
      prune: true
      selfHeal: true