apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: monitoring
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  source:
    repoURL: https://github.com/Mallikarjun-Atanoor/k8s-gitops-microservices.git
    targetRevision: main
    path: monitoring

    kustomize:
      buildOptions: --enable-helm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true